#!/usr/bin/env python3
"""
Embed all audio assets (music + SFX) into the executable as C++ byte arrays.

Emits:
  - include/audio_data.hpp   (extern declarations)
  - src/audio_data.cpp       (byte-array definitions, compiled into the binary)

Music arrays are consumed by SoundManager via sf::Music::openFromMemory()
(streaming, low RAM). SFX arrays are consumed via
sf::SoundBuffer::loadFromMemory() (decoded to RAM, suitable for short clips).

Usage:
    python tools/embed_audio.py

Re-run whenever assets/music/ or assets/sfx/ change.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (symbol_suffix, relative_path, kind)
ASSETS = [
    # --- Music (streamed via sf::Music::openFromMemory) ---
    ("music_arcade",    "assets/music/arcade.ogg",    "music"),
    ("music_katana",    "assets/music/katana.ogg",    "music"),
    ("music_rigel",     "assets/music/rigel.ogg",     "music"),
    ("music_synthwave", "assets/music/synthwave.ogg", "music"),
    # --- SFX (loaded via sf::SoundBuffer::loadFromMemory) ---
    ("sfx_platform_hit", "assets/sfx/platform_hit.wav", "sfx"),
    ("sfx_brick_hit",    "assets/sfx/brick_hit.wav",    "sfx"),
    ("sfx_wall_hit",     "assets/sfx/wall_hit.wav",     "sfx"),
]


def emit(symbol: str, rel_path: str, header_lines: list, cpp_lines: list) -> int:
    path = os.path.join(ROOT, rel_path.replace("/", os.sep))
    if not os.path.isfile(path):
        print(f"error: missing input file: {path}", file=sys.stderr)
        sys.exit(1)

    with open(path, "rb") as f:
        data = f.read()
    size = len(data)

    var = f"{symbol}_data"
    size_var = f"{symbol}_size"

    header_lines.append(f"extern const unsigned char {var}[];")
    header_lines.append(f"extern const unsigned long {size_var};")
    header_lines.append("")

    cpp_lines.append(f"// {rel_path} ({size} bytes)")
    cpp_lines.append(f"const unsigned char {var}[] = {{")
    for i in range(0, size, 12):
        chunk = data[i:i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        cpp_lines.append(f"    {hex_vals},")
    cpp_lines.append("};")
    cpp_lines.append(f"const unsigned long {size_var} = {size}ul;")
    cpp_lines.append("")

    return size


def main() -> None:
    header_lines = [
        "#ifndef BREAKOUT_AUDIO_DATA",
        "#define BREAKOUT_AUDIO_DATA",
        "",
        "// AUTO-GENERATED by tools/embed_audio.py - do not edit by hand.",
        "// Declares byte arrays embedding all audio (music + SFX) into the binary.",
        "",
        "#include <cstddef>",
        "",
    ]
    cpp_lines = [
        '#include "audio_data.hpp"',
        "",
        "// AUTO-GENERATED by tools/embed_audio.py - do not edit by hand.",
        "",
    ]

    total = 0
    for symbol, rel_path, _ in ASSETS:
        total += emit(symbol, rel_path, header_lines, cpp_lines)

    header_lines.append("#endif // BREAKOUT_AUDIO_DATA")

    header_path = os.path.join(ROOT, "include", "audio_data.hpp")
    cpp_path = os.path.join(ROOT, "src", "audio_data.cpp")
    with open(header_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header_lines) + "\n")
    with open(cpp_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(cpp_lines) + "\n")

    print(f"Embedded {len(ASSETS)} audio assets ({total} bytes total).")
    print(f"  -> {os.path.relpath(header_path, ROOT)}")
    print(f"  -> {os.path.relpath(cpp_path, ROOT)}")


if __name__ == "__main__":
    main()